networks:
  inception_net:
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    # 기본 볼륨 드라이버 경로를 local로 설정
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/mariadb
      # bind 옵션을 사용하여 호스트와 컨테이너의 디렉토리를 연결
      # read-write로 설정하여 읽기/쓰기가 가능하도록 설정
      o: bind

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/wordpress
      o: bind

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    # 구동 실패 시 재시도
    restart: always
    init: true
    build:
      # Dockerfile 경로 지정
      context: ./requirements/mariadb
      args:
        # 환경변수로 전달
        - DB_NAME=${DB_NAME}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      # 볼륨 연결
      # 컨테이너 내부의 /var/lib/mysql 디렉토리와 호스트의 ${DATA_PATH}/mariadb 디렉토리를 연결
      - mariadb:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    init: true
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      args:
        - WP_DB_NAME=${DB_NAME}
        - WP_DB_HOST=${DB_HOST}
        - WP_DB_USER=${DB_USER}
        - WP_DB_PASSWORD=${DB_PASSWORD}
        - WP_URL=${WP_URL}
        - WP_TITLE=${WP_TITLE}
        - WP_ADMIN_USER=${WP_ADMIN_USER}
        - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
        - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
        - WP_LOCALE=${WP_LOCALE}
        - WP_USER=${WP_USER}
        - WP_USER_PASSWORD=${WP_USER_PASSWORD}
        - WP_USER_EMAIL=${WP_USER_EMAIL}
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_net
    env_file:
      # 환경변수 파일 경로 지정
      - .env

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    init: true
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    volumes:
      - wordpress:/var/www/html
    ports:
      # 호스트의 443 포트와 컨테이너의 443 포트를 연결
      # host:container
      - "443:443"
    networks:
      - inception_net
