FROM alpine:3.19

ARG WP_DB_NAME \
    WP_DB_HOST \
    WP_DB_USER \
    WP_DB_PASSWORD \
    WP_URL \
    WP_TITLE \
    WP_ADMIN_USER \
    WP_ADMIN_PASSWORD \
    WP_ADMIN_EMAIL \
    WP_LOCALE \
    WP_USER \
    WP_USER_PASSWORD \
    WP_USER_EMAIL

# add user
RUN addgroup -S wordpress && adduser -G wordpress -S wordpress -H -s /sbin/nologin wordpress && \
    addgroup -S nginx && adduser -G nginx -S nginx

COPY ./tools/wp_config_create.sh /tmp/wp_config_create.sh
COPY ./tools/wp_entry.sh /tmp/wp_entry.sh
COPY ./conf/wordpress.conf /etc/php82/php-fpm.d/www.conf

# install
RUN apk update && apk upgrade && \
    apk add --no-cache php82 \
                        php82-fpm \
                        php82-curl \
                        php82-mysqli \
                        php82-mbstring \
                        php82-phar \
                        php82-pdo \
                        php82-pdo_mysql \
                        wget \
                        mariadb-client && \
    mkdir -p /var/www/html && \
    chown -R wordpress:wordpress /var/www/html && \
    wget https://wordpress.org/latest.zip && \
    unzip latest.zip && \
    mv wordpress/* /var/www/html && \
    rm -rf latest.zip wordpress && \
    wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

WORKDIR /var/www/html

# RUN rm -rf index.html

RUN chmod 755 /tmp/wp_config_create.sh && \
    chmod 755 /tmp/wp_entry.sh && \
    /bin/sh /tmp/wp_config_create.sh && \
    rm -rf /tmp/wp_config_create.sh
    
RUN mkdir -p /var/log/php82 && \
    chmod 755 /var/log/php82 && \
    chown -R nginx:nginx /var/log/php82

ENTRYPOINT ["/bin/sh", "/tmp/wp_entry.sh"]
CMD ["php-fpm82", "-F"]